name: CI

on:
  push:
    branches:
      - main
      - reusable-workflow
      - remote-reusable 
  pull_request:

jobs:
  call-reusable-ci:
    uses: venerari/reusable-ci/.github/workflows/reusable-ci.yml@main
    with:
      image_name: venerayan/node-hello
      dockerhub_username: venerayan
      push_image: ${{ github.event_name != 'pull_request' }}
      run_sonar: true
    secrets: inherit